"""09_steps

Revision ID: 4755a7a3bcfc
Revises: 67e13a90405d
Create Date: 2025-04-11 23:11:18.591027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4755a7a3bcfc'
down_revision: Union[str, None] = '67e13a90405d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('new_submission', sa.Boolean(), nullable=False))
    op.add_column('step_attempts', sa.Column('submitted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('step_comments_files', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('step_comments_files', sa.Column('mimetype', sa.String(), nullable=False))
    op.add_column('step_comments_files', sa.Column('size', sa.Float(), nullable=False))
    op.add_column('step_files', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('step_files', sa.Column('mimetype', sa.String(), nullable=False))
    op.add_column('step_files', sa.Column('size', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step_files', 'size')
    op.drop_column('step_files', 'mimetype')
    op.drop_column('step_files', 'name')
    op.drop_column('step_comments_files', 'size')
    op.drop_column('step_comments_files', 'mimetype')
    op.drop_column('step_comments_files', 'name')
    op.drop_column('step_attempts', 'submitted_at')
    op.drop_column('projects', 'new_submission')
    # ### end Alembic commands ###
