"""04_projects

Revision ID: 63db22ab021b
Revises: afb83c4969aa
Create Date: 2025-03-19 14:31:26.304314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63db22ab021b'
down_revision: Union[str, None] = 'afb83c4969aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'document_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'document_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
