"""08_steps

Revision ID: 67e13a90405d
Revises: ba0aaad72ceb
Create Date: 2025-03-27 10:57:16.300931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67e13a90405d'
down_revision: Union[str, None] = 'ba0aaad72ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_attempts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('step_id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_attempts_step_id'), 'step_attempts', ['step_id'], unique=False)
    op.create_table('step_comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('step_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_comments_step_id'), 'step_comments', ['step_id'], unique=False)
    op.create_index(op.f('ix_step_comments_user_id'), 'step_comments', ['user_id'], unique=False)
    op.create_table('step_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('step_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_files_step_id'), 'step_files', ['step_id'], unique=False)
    op.create_table('step_comments_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['step_comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_comments_files_comment_id'), 'step_comments_files', ['comment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_step_comments_files_comment_id'), table_name='step_comments_files')
    op.drop_table('step_comments_files')
    op.drop_index(op.f('ix_step_files_step_id'), table_name='step_files')
    op.drop_table('step_files')
    op.drop_index(op.f('ix_step_comments_user_id'), table_name='step_comments')
    op.drop_index(op.f('ix_step_comments_step_id'), table_name='step_comments')
    op.drop_table('step_comments')
    op.drop_index(op.f('ix_step_attempts_step_id'), table_name='step_attempts')
    op.drop_table('step_attempts')
    # ### end Alembic commands ###
