"""07_teams

Revision ID: ba0aaad72ceb
Revises: a8c4380c72d4
Create Date: 2025-03-23 22:28:35.299554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba0aaad72ceb'
down_revision: Union[str, None] = 'a8c4380c72d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_team_members_participant_id', table_name='team_members')
    op.create_index(op.f('ix_team_members_participant_id'), 'team_members', ['participant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_members_participant_id'), table_name='team_members')
    op.create_index('ix_team_members_participant_id', 'team_members', ['participant_id'], unique=False)
    # ### end Alembic commands ###
