"""02_users

Revision ID: dba930bdd1ce
Revises: 9cd336b6f493
Create Date: 2025-03-18 20:25:35.237602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba930bdd1ce'
down_revision: Union[str, None] = '9cd336b6f493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'birth_date')
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birth_date')
    op.add_column('participants', sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
